version: '3.4'

services:
  rabbitmq:
    container_name: "rabbitmq"  # Corrected the container name
    environment:
       - RABBITMQ_DEFAULT_USER=user
       - RABBITMQ_DEFAULT_PASS=mypass
    ports:
       # RabbitMQ Instance
       - '5672:5672'
       # Web Interface
       - '15672:15672' 
    networks:
      - mynetwork  # Add this network configuration

  consumer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5001;
    ports:
      - "5001:5001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - mynetwork  # Add this network configuration
    depends_on:
      - postgres

  producer.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:5002;
    ports:
      - "5002:5002"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    networks:
      - mynetwork  # Add this network configuration
    depends_on:
      - postgres

  postgres:
    image: postgres
    container_name: "postgres"
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    networks:
      - mynetwork
networks:
  mynetwork:  # Define a custom network for the services
